/* eslint-disable no-console */
/**
 * db:seed - turns the repo's src/config/site.ts into Supabase-ready content.
 *
 *   npm run db:seed            # writes supabase/seed.sql (no secrets, no network)
 *   npm run db:seed -- --push  # upserts straight into site_settings
 *
 * The default mode is deliberately keyless: paste the generated file into the
 * Supabase SQL editor. Direct mode needs SUPABASE_SERVICE_ROLE_KEY in
 * `.env.seed.local` (gitignored) — never in `.env.local`, which the Next.js
 * app loads and would expose to the browser bundle boundary.
 */
import fs from "node:fs";
import path from "node:path";
import dotenv from "dotenv";
import { createClient } from "@supabase/supabase-js";
import { site } from "../src/config/site";
import {
  contactSchema,
  estimatorSchema,
  processListSchema,
  projectListSchema,
  serviceListSchema,
  siteSchema,
  statsListSchema,
  testimonialListSchema,
} from "../src/lib/validate";

const push = process.argv.includes("--push");
const root = process.cwd();

const siteValue = {
  tagline: site.tagline,
  heroSupport: site.heroSupport,
  location: site.location,
  founder: { quote: site.founder.quote, role: site.founder.role },
  ui: { ...site.ui },
  showTestimonials: site.showTestimonials,
};

const sections: { key: string; value: unknown }[] = [
  { key: "projects", value: site.projects },
  { key: "services", value: site.services },
  { key: "testimonials", value: site.testimonials },
  { key: "stats", value: site.stats },
  { key: "process", value: site.process },
  { key: "site", value: siteValue },
  { key: "contact", value: site.contact },
  { key: "estimator", value: site.estimator },
];

const schemas: Record<string, { safeParse: (v: unknown) => { success: boolean } }> = {
  projects: projectListSchema,
  services: serviceListSchema,
  testimonials: testimonialListSchema,
  stats: statsListSchema,
  process: processListSchema,
  site: siteSchema,
  contact: contactSchema,
  estimator: estimatorSchema,
};

function validatedSections(): { key: string; value: unknown }[] {
  const out: { key: string; value: unknown }[] = [];
  for (const section of sections) {
    const parsed = schemas[section.key].safeParse(section.value);
    if (!parsed.success) {
      console.error(`Section "${section.key}" failed its schema - skipping.`);
      continue;
    }
    out.push(section);
  }
  return out;
}

function sqlText(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function sqlJsonb(value: unknown): string {
  return `'${JSON.stringify(value).replace(/'/g, "''")}'::jsonb`;
}

function writeSqlFile(valid: { key: string; value: unknown }[]): string {
  const rows = valid.map((s) => `  (${sqlText(s.key)}, ${sqlJsonb(s.value)})`).join(",\n");
  const contents = [
    "-- Generated by `npm run db:seed` from src/config/site.ts. Do not edit by hand.",
    "-- Paste into the Supabase SQL editor (runs as postgres, so no key is needed).",
    "",
    "begin;",
    "",
    "delete from public.site_settings;",
    "",
    "insert into public.site_settings (key, value) values",
    rows,
    "on conflict (key) do update set value = excluded.value, updated_at = now();",
    "",
    "commit;",
    "",
  ].join("\n");

  const target = path.join(root, "supabase", "seed.sql");
  fs.writeFileSync(target, contents, "utf8");
  return target;
}

function envHasServiceKey(file: string): boolean {
  if (!fs.existsSync(file)) return false;
  return /^SUPABASE_SERVICE_ROLE_KEY\s*=/m.test(fs.readFileSync(file, "utf8"));
}

async function pushDirect(valid: { key: string; value: unknown }[]): Promise<void> {
  if (envHasServiceKey(path.join(root, ".env.local"))) {
    console.error("FAIL: SUPABASE_SERVICE_ROLE_KEY is sitting in .env.local.");
    console.error("      The Next.js app reads .env.local - move the key to .env.seed.local.");
    process.exit(1);
  }

  dotenv.config({ path: path.join(root, ".env.seed.local"), quiet: true });
  dotenv.config({ path: path.join(root, ".env"), quiet: true });

  const url = process.env.SUPABASE_URL ?? process.env.NEXT_PUBLIC_SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!url || !key) {
    console.error("Missing SUPABASE_URL (or NEXT_PUBLIC_SUPABASE_URL) and SUPABASE_SERVICE_ROLE_KEY.");
    console.error("Put them in .env.seed.local, or drop --push and run `npm run db:seed` to");
    console.error("get a keyless supabase/seed.sql instead.");
    process.exit(1);
  }

  console.warn("!! Pushing with a service-role key read from .env.seed.local (gitignored).");
  console.warn("!! Never commit that key and never move it into .env.local.");

  const supabase = createClient(url, key, { auth: { persistSession: false } });

  const { error: delErr } = await supabase.from("site_settings").delete().neq("key", "__never__");
  if (delErr) {
    console.error("Failed to clear site_settings:", delErr.message);
    process.exit(1);
  }

  for (const section of valid) {
    const { error } = await supabase
      .from("site_settings")
      .upsert({ key: section.key, value: section.value }, { onConflict: "key" });
    if (error) {
      console.error(`Failed to upsert "${section.key}":`, error.message);
      process.exit(1);
    }
    console.log(`ok ${section.key}`);
  }

  console.log("\nSeed complete. The admin dashboard now mirrors src/config/site.ts.");
}

async function main() {
  const valid = validatedSections();

  if (push) {
    await pushDirect(valid);
    return;
  }

  const target = writeSqlFile(valid);
  console.log(`Wrote ${target} (${valid.length} sections, no secrets involved).`);
  console.log("Run it in the Supabase SQL editor, or pass --push for a direct upsert.");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
